void init_interface();
int get_sizerow();
int get_sizecol();
WINDOW* get_mapwin();
void menu();
int createmap_win();
int createmsg_win();
void refresh_allgame();
int click_frodooption();
void frodo_colect(unit *chr);
void change_hobbit(int row, int col);
void move_msg(int n);
void quit_answer();
void load_answer();
