void init_interface();
void get_dimension();
int get_sizerow();
int get_sizecol();
WINDOW* get_mapwin();
WINDOW* create_win(int win_y, int win_x, int starty, int startx);
void destroy_win(WINDOW **local_win);
void menu();
int click_option(int option);
void wprintw_menu(int highlight);
void printw_scroll();
int createmap_win();
int createhobbit_win();
void refresh_allgame();
void click_frodooption();
void frodo_colect(unit *chr);
